### ISSUE TITLE
[Feature Request] PDF Export

### ISSUE THREAD

**Issue by codello** [8fuhst/MafiAStarLite-frontend#5]
One use case that I have with some regularity is the need to print out a list of all songs. It would be very convenient if MafiAStar offered a possibility to generate a PDF file that can be printed. Because generating PDFs can sometimes be a little tricky it might be easier to provide a download in another format (CSV, LaTeX or something) that can be processed further. If needed I can provide a the LaTeX template I currently use.

**Comment by 8fuhst** [comment]
Songlist is now available. This repository will no longer be maintained as the frontend has been merged with the backend in a single repository at https://github.com/8fuhst/MafiAStarLite. Please open future issues there
